server:
  port: 1002
spring:
  application:
    name: swallow-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wanghanMaYun/swallow_config.git
          username: 493985762@qq.com
          password: wanghan076
          basedir: D:\swallow_config
eureka:
  instance:
    hostname: localhost
    # 心跳检测检测与续约时间
    lease-renewal-interval-in-seconds: 5
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/